all :
	gcc -m64 -shared -c src/main/c/cpucheck.c -o target/libcpucheck.so
	gcc -m64 -shared -c src/main/c/memorycheck.c -o target/libmemorycheck.so
	gcc -m64 -shared -c src/main/c/gradualincreasecheck.c -o target/libgradualincreasecheck.so
